
services:
  firebird:
    image: jacobalberty/firebird:3.0
    container_name: firebird
    ports:
      - "3050:3050"
    environment:
      - ISC_PASSWORD=${ISC_PASSWORD}
    volumes:
      - /home/infobrasilroot/api-tray/database/firebird:/firebird/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3333:3333"
    depends_on:
      - redis
      - firebird
    volumes:
      - /home/infobrasilroot/api-tray/logs/api:/var/log/integracao-tray  # Logs da API vão para /api-tray/logs/api

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: node build/worker.js
    depends_on:
      - redis
      - firebird
    restart: always
    volumes:
      - /home/infobrasilroot/api-tray/logs/worker:/var/log/integracao-tray  # Logs do Worker vão para /api-tray/logs/worker

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
