
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:80" 
    volumes:
      - /home/infobrasilroot/api-tray/logs/api:/var/log/integracao-tray  # Logs da API vão para /api-tray/logs/api

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: node build/worker.js
    depends_on:
      - redis
    restart: always
    volumes:
      - /home/infobrasilroot/api-tray/logs/worker:/var/log/integracao-tray  # Logs do Worker vão para /api-tray/logs/worker

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
