version: '3.8'

services:
  api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: node dist/index.js  
    depends_on:
      - redis_server
    volumes:
      - logs:/var/log/myapp  # Monta o diretório de logs no host

  worker:
    build:
      context: .
    env_file:
      - .env
    command: node dist/worker.js 
    depends_on:
      - redis_server
    volumes:
      - logs:/var/log/myapp  # Monta o diretório de logs no host

  scheduler:
    build:
      context: .
    env_file:
      - .env
    command: node dist/scheduler.js
    depends_on:
      - redis_server
    volumes:
      - logs:/var/log/myapp  # Monta o diretório de logs no host

  redis_server:
    image: redis:latest
    container_name: redis_server
    ports:
      - '6379:6379'
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  redis_data:
  logs:  # Volume para armazenar logs fora dos contêineres
