version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3333:3333"
    depends_on:
      - redis
    volumes:
      - ./logs/api:/var/log/integracao-tray  # Mapeia os logs da API para o host

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: node build/shared/http/queue.js
    depends_on:
      - redis
    restart: always
    volumes:
      - ./logs/worker:/var/log/integracao-tray  # Mapeia os logs do Worker para o host

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
