services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: [.env]
    ports:
      - "3333:3333"
    volumes:
      - /home/infobrasilroot/api-tray/logs/api:/var/log/integracao-tray
    restart: always
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: [.env]
    command: node build/queue/worker.js
    depends_on:
      - redis
    restart: always
    volumes:
      - /home/infobrasilroot/api-tray/logs/worker:/var/log/integracao-tray

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: [.env]
    command: node build/scheduler.js
    depends_on:
      - redis
    restart: "no" # roda, registra schedulers no Redis e sai

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
